# Databricks notebook source
"""Defining all config variables """
dst_catalogue_name = "workspace"
bronze_dst_schema_name = "bronze"
silver_dst_schema_name = "silver"
gold_dst_schema_name = "gold"
orders_source_path = "/Volumes/workspace/source/raw_files/Orders.json"
customer_source_path = "/Volumes/workspace/source/raw_files/Customer.xlsx"
products_source_path = "/Volumes/workspace/source/raw_files/Products.csv"
products_source_type = "csv"
customer_source_type = "xlsx"
orders_source_type = "json"
bronze_orders_dst_table_name = "bronze_orders"
silver_orders_dst_table_name = "silver_orders"
bronze_customer_dst_table_name = "bronze_customer"
silver_customer_dst_table_name = "silver_customer"
bronze_products_dst_table_name = "bronze_products"
silver_products_dst_table_name = "silver_products"
gold_dst_table_name = "profit"
